//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessIdentifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReasonText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReasonText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessIdentifier.ReasonText", typeof(ReasonText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Business Identifier checksum &apos;{0}&apos; does not match to calculated value &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_ChecksumMismatch {
            get {
                return ResourceManager.GetString("ERR_ChecksumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Merkkijono ei voi sisältää pelkkiä 0-merkkejä..
        /// </summary>
        internal static string ERR_EiPelkkaaNollaa {
            get {
                return ResourceManager.GetString("ERR_EiPelkkaaNollaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Input string &apos;{0}&apos; is not in valid Business Identifier format..
        /// </summary>
        internal static string ERR_EiYTunnus {
            get {
                return ResourceManager.GetString("ERR_EiYTunnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Could not calculate Business Identifier checksum (reminder can not be 1)..
        /// </summary>
        internal static string ERR_ReminderOne {
            get {
                return ResourceManager.GetString("ERR_ReminderOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Empty input string..
        /// </summary>
        internal static string ERR_TyhjaSyote {
            get {
                return ResourceManager.GetString("ERR_TyhjaSyote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN: Input string did not contain dash (&apos;-&apos;).
        /// </summary>
        internal static string WARN_NoDash {
            get {
                return ResourceManager.GetString("WARN_NoDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARN: Input string was not correct length (or was old format with 6 numbers)..
        /// </summary>
        internal static string WARN_TooShort {
            get {
                return ResourceManager.GetString("WARN_TooShort", resourceCulture);
            }
        }
    }
}
